title: Manoa trade your stuff
description: ----NEED ADD DESCRIPTION----
google_analytics:
show_downloads: false
theme: minima
github:
  is_project_page: true
  repository_url: https://github.com/manoa-trade-your-stuff/manoa-trade-your-stuff
gems:
  - jekyll-mentions
